    - name: Install MySQL Service
      become: yes
      apt: name={{ item }} state=present
      with_items:
        - mysql-server
        - mysql-client

    - name: Start MySQL Service
      become: yes
      service:
          name: mysql
          state: started
          enabled: yes

    - name: Create Application DB
      become: yes
      mysql_db: 
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ db_name }}"
        state: present

    - name: Create DB user
      become: yes
      mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_password }}"
      priv: '*.*:ALL'
      state: present   
      host: '%'

